# Generated by Django 3.2.6 on 2021-08-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0007_todo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
