# Generated by Django 3.2.6 on 2021-09-06 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0010_alter_todo_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='text',
            new_name='title',
        ),
    ]
