# Generated by Django 3.2.9 on 2021-12-06 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_phoneimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='image',
        ),
    ]
